LPARAMETERS lnCPF AS NUMBER
LOCAL lcCPFCorr AS STRING

IF VARTYPE(lnCPF) <> "N"
    RETURN MESSAGEBOX('CPF inválido.', 0+48)
ENDIF

IF LEN(STR(lnCPF)) <> 11
    RETURN MESSAGEBOX('CPF inválido.', 0+48)
ENDIF

lcCPFCorr = TRANSFORM(lnCPF, "999,999,999-99")

RETURN lcCPFCorr